language: java

branches:
  only:
  - master
  - dev

sudo:	required
os:	linux

services:
  - docker

jobs:
  include:
    - stage: docker 'production - admin' build test
      script: sudo docker build -t prod-admin --build-arg profiles=production --build-arg projects=admin .

    - stage: docker 'production - api' build test
      script:	sudo docker build -t prod-api --build-arg profiles=production --build-arg projects=api .
