spring:
  profiles:
    include: production-core
  jackson:
    serialization:
      fail_on_empty_beans:  false
  http:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
server:
  port: 8080
  display-name: www.half-handicraft.com

