#!/bin/bash

echo ${PROJECTS}
echo ${PROFILES}
echo ${IMAGE_NAME}
echo ${SOURCE_BRANCH}
echo ${COMMIT_MSG}
echo ${DOCKER_REPO}

docker build -t $IMAGE_NAME --build-arg profiles=${PROFILES} --build-arg projects=${PROJECTS} .
